# The URL the site will be built for
base_url = "https://snapshotmanager.github.io"
theme = "cela"
title = "Snapshot Manager"
description = "Easy to use snapshot management for Linux."
default_language = "en"

# Output directory `public` (by default)
output_dir = "public"

# Whether dotfiles at the root level of the output directory are preserved when (re)building the site.
# Enabling this also prevents the deletion of the output folder itself on rebuilds.
# [Cela hint] Cela will enable this feature by default
preserve_dotfiles_in_output = true

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = false

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = []

# Similar to ignored_content, a list of glob patterns specifying asset files to
# ignore when the static directory is processed. Defaults to none, which means
# that all asset files are copied over to the `public` directory
ignored_static = []

# When set to "true", a feed is automatically generated.
# [Cela hint] Cela will enable this feature by default for rss feed.
generate_feeds = true

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
# [Cela hint] Cela will set the feed limit to 50 by default
feed_limit = 50

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", feed = true},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => üòÑ)
render_emoji = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `‚Ä¶`, `"quote"` into `‚Äúcurly‚Äù` etc
smart_punctuation = false

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
# Default to open
# Reference [Github Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes)
bottom_footnotes = true

[slugify]
# default is on
paths = "on"
# default is on (slugify the categories and tags ..)
taxonomies = "on"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
paths_keep_dates = false

[extra]
# Put all your custom variables here
# Whether open the TOC on each page
toc_open = false

# Whether to use mathjax on each page
# default false
enable_mathjax = false

[extra.cela]
# The template title (shown in home page )
default_keywords = ["Snapshot", "Snapshot Manager", "Snapshots", "Linux"]
favicon = "snapm-favicon.ico"
favicon16x16 = "snapm-favicon-16x16.png"
favicon32x32 = "snapm-favicon-32x32.png"
header_title = "Snapshot Manager"
icon = "svg/cela_new_small_rec.svg"
icon_dark = "svg/cela_new_small_rec.svg"

date_format = "%Y-%m-%d"
show_home_title = true
home_title = "Snapshot Manager"
navigation = [
  {path = "/", title = "Archive"},
  {path = "/tags", title = "Tags"},
  {path = "/categories", title = "Categories"},
#  {path = "#", title = "Search", is_search = true},
#  {path = "/robot", title = "Robot", is_robot = true},
  {path = "https://getzola.org/", title = "Zola", is_external = true},
]

show_home_content = true
home_content = "Welcome to the Snapshot Manager docs site!"
# The default home directory you will write your blog post content
# This will be used to generate the home page (with subsections) posts list
# If you set this to "", the all the content under "content" will be shown (not recommand)
# If you set this to "blog", the all the content under "content/blog" will be shown (recommand)
home_content_dir = "blog"
# [Cela hint] Use "mix" to show subsections as an archieve on home page with collapsible lists
# TODO fix "" empty string
home_list_style = "default"

show_home_social_icons = true
social_icons = [
  {path = "https://github.com/snapshotmanager", title = "GitHub", icon = "github"},
  {path = "bmr@redhat.com", title = "Email", icon = "email"},
  {path = "https://github.com/snapshotmanager/snapm/wiki", title = "Wiki", icon = "wiki"},
  {path = "/atom.xml", title = "RSS", icon = "rss"},
]
taxonomies_desc = []
taxonomies_tail = [
  {name = "tags", emoji = "üè∑Ô∏è "},
  {name = "categories", emoji = "üìÇ"},
]

# Trigger when readers click the "suggest changes" on each page
# it can be
# - an email address (e.g. "mailto:edward@edwardzcn.me" )
# - a github or gitlab repo link (e.g. "https://github.com/<your-username>/<your-source>/tree/main")
# if your blog source is public, cela will try to find the orinal page with its relative path
#edit_post_url = "mailto:your-username@gmail.com"
edit_post_url = "https://github.com/snapshotmanager/snapshotmanager-docs/tree/main"
show_cela_logo = true
show_code_copy_buttons = true
show_header_title = false
show_post_edit_button = true
show_post_meta = true
show_post_nav_links = true
show_reading_time = true
show_scroll_to_top = true
show_taxonomies_description = true
show_taxonomies_tail = true
show_theme_toggle = true
show_toc = true
unfold_toc = false
show_word_count = true

# [Cela hint] Cela will use this for search page title (default is "Search" if not set)
search_title = "From Config: Search"
# [Cela hint] Cela will use this for search page description (default is "Find posts by title or body content" if not set)
search_description = "From Config: Find posts by title or body content"

[extra.cela.color]

default_theme = "dark"
# If disable javascript, the website will always use the default_theme
remember_choice = true
# If remeber_choice is true, the cookie/localStorage will use the theme last time user visited

[extra.cela.global]
# Whether to show the original title defined in base configure
title_show = true
# Title prefix/delimiter before page or section title
title_prefix = "üåü"
# The internationalization directory for multi-language support
i18n_dir = "i18n_dir"

# # TODO
# # Whether to load social icons (default = true)
# social_icon = true
# # Specify the directory of social icon (default = "") If set, the original social_icon macro will not be loaded and used
# social_icon_dir = "auto"

